import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency } from '@shared/utils/formatters';

// PDF-specific currency formatter to ensure proper rendering
const formatCurrencyForPDF = (amount) => {
  // Format number with proper comma separation
  const num = Number(amount);
  
  // Convert to string with 2 decimal places
  const formatted = num.toFixed(2);
  
  // Add commas for Indian numbering system
  const parts = formatted.split('.');
  const integerPart = parts[0];
  const decimalPart = parts[1];
  
  // Indian number system: last 3 digits, then groups of 2
  let lastThree = integerPart.substring(integerPart.length - 3);
  const otherNumbers = integerPart.substring(0, integerPart.length - 3);
  
  if (otherNumbers !== '') {
    lastThree = ',' + lastThree;
  }
  
  const formattedInteger = otherNumbers.replace(/\B(?=(\d{2})+(?!\d))/g, ',') + lastThree;
  
  // Return with Rs. prefix
  return `Rs. ${formattedInteger}.${decimalPart}`;
};

// Helper to format date
const formatDate = (date) => {
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
};

// Add header to PDF
const addHeader = (doc, title, restaurantName = 'QR Menu Restaurant') => {
  // Add logo/brand area
  doc.setFillColor(79, 70, 229); // Indigo
  doc.rect(0, 0, 210, 40, 'F');
  
  // Restaurant name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(restaurantName, 15, 20);
  
  // Report title
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(title, 15, 30);
  
  // Date
  doc.setFontSize(10);
  doc.text(`Generated: ${formatDate(new Date())}`, 150, 30);
  
  doc.setTextColor(0, 0, 0);
};

// Add footer
const addFooter = (doc, pageNumber, totalPages) => {
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text(
    `Page ${pageNumber} of ${totalPages}`,
    105,
    285,
    { align: 'center' }
  );
  doc.text(
    'Generated by QR Menu Analytics System',
    105,
    290,
    { align: 'center' }
  );
};

// Export Revenue Report
export const exportRevenueReport = (stats, period, restaurantName) => {
  const doc = new jsPDF();
  
  addHeader(doc, 'Revenue Analysis Report', restaurantName);
  
  let yPos = 50;
  
  // Summary Section
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(79, 70, 229);
  doc.text('Revenue Summary', 15, yPos);
  yPos += 10;
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  
  const summaryData = [
    ['Metric', 'Value'],
    ['Total Revenue', formatCurrencyForPDF(stats.revenue.total)],
    ['Pending Revenue', formatCurrencyForPDF(stats.revenue.pending)],
    ['Today\'s Revenue', formatCurrencyForPDF(stats.revenue.today)],
    ['Daily Average', formatCurrencyForPDF(stats.revenue.daily)],
    ['Average Order Value', formatCurrencyForPDF(stats.revenue.average)],
    ['Revenue Growth', `${stats.revenue.growth > 0 ? '+' : ''}${stats.revenue.growth.toFixed(2)}%`]
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [summaryData[0]],
    body: summaryData.slice(1),
    theme: 'grid',
    headStyles: { fillColor: [79, 70, 229], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    margin: { left: 15, right: 15 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Revenue Trend
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(79, 70, 229);
  doc.text('7-Day Revenue Trend', 15, yPos);
  yPos += 10;
  
  const trendData = [
    ['Date', 'Orders', 'Revenue']
  ];
  
  stats.revenueTrend.forEach(day => {
    trendData.push([
      formatDate(day.date),
      day.orders.toString(),
      formatCurrencyForPDF(day.revenue)
    ]);
  });
  
  autoTable(doc, {
    startY: yPos,
    head: [trendData[0]],
    body: trendData.slice(1),
    theme: 'striped',
    headStyles: { fillColor: [16, 185, 129], fontStyle: 'bold' },
    margin: { left: 15, right: 15 }
  });
  
  addFooter(doc, 1, 1);
  
  doc.save(`Revenue_Report_${period}_${Date.now()}.pdf`);
};

// Export Orders Report
export const exportOrdersReport = (stats, period, restaurantName) => {
  const doc = new jsPDF();
  
  addHeader(doc, 'Orders Analysis Report', restaurantName);
  
  let yPos = 50;
  
  // Order Summary
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(79, 70, 229);
  doc.text('Order Summary', 15, yPos);
  yPos += 10;
  
  const orderSummary = [
    ['Metric', 'Count', 'Percentage'],
    ['Total Orders', stats.orders.total.toString(), '100%'],
    ['Completed', stats.orders.completed.toString(), `${((stats.orders.completed / stats.orders.total) * 100).toFixed(1)}%`],
    ['Pending', stats.orders.pending.toString(), `${((stats.orders.pending / stats.orders.total) * 100).toFixed(1)}%`],
    ['Preparing', stats.orders.preparing.toString(), `${((stats.orders.preparing / stats.orders.total) * 100).toFixed(1)}%`],
    ['Ready', stats.orders.ready.toString(), `${((stats.orders.ready / stats.orders.total) * 100).toFixed(1)}%`],
    ['Cancelled', stats.orders.cancelled.toString(), `${((stats.orders.cancelled / stats.orders.total) * 100).toFixed(1)}%`]
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [orderSummary[0]],
    body: orderSummary.slice(1),
    theme: 'grid',
    headStyles: { fillColor: [79, 70, 229], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    margin: { left: 15, right: 15 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Hourly Distribution
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(79, 70, 229);
  doc.text('Hourly Distribution', 15, yPos);
  yPos += 10;
  
  const hourlyData = [['Hour', 'Orders', 'Revenue']];
  stats.hourlyDistribution
    .filter(h => h.orders > 0)
    .forEach(hour => {
      const time = hour.hour === 0 ? '12 AM' : 
                   hour.hour < 12 ? `${hour.hour} AM` :
                   hour.hour === 12 ? '12 PM' :
                   `${hour.hour - 12} PM`;
      hourlyData.push([
        time,
        hour.orders.toString(),
        formatCurrencyForPDF(hour.revenue)
      ]);
    });
  
  autoTable(doc, {
    startY: yPos,
    head: [hourlyData[0]],
    body: hourlyData.slice(1),
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246], fontStyle: 'bold' },
    margin: { left: 15, right: 15 }
  });
  
  addFooter(doc, 1, 1);
  
  doc.save(`Orders_Report_${period}_${Date.now()}.pdf`);
};

// Export Menu Performance Report
export const exportMenuReport = (stats, period, restaurantName) => {
  const doc = new jsPDF();
  
  addHeader(doc, 'Menu Performance Report', restaurantName);
  
  let yPos = 50;
  
  // Top Selling Items
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(79, 70, 229);
  doc.text('Top Selling Items', 15, yPos);
  yPos += 10;
  
  const menuData = [['Rank', 'Item Name', 'Quantity Sold', 'Revenue']];
  
  stats.popularItems.slice(0, 10).forEach((item, index) => {
    menuData.push([
      `#${index + 1}`,
      item.name,
      item.quantity.toString(),
      formatCurrencyForPDF(item.revenue)
    ]);
  });
  
  autoTable(doc, {
    startY: yPos,
    head: [menuData[0]],
    body: menuData.slice(1),
    theme: 'grid',
    headStyles: { fillColor: [236, 72, 153], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    margin: { left: 15, right: 15 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Performance Metrics
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(79, 70, 229);
  doc.text('Performance Metrics', 15, yPos);
  yPos += 10;
  
  const totalItems = stats.popularItems.reduce((sum, item) => sum + item.quantity, 0);
  const totalRevenue = stats.popularItems.reduce((sum, item) => sum + item.revenue, 0);
  
  const metricsData = [
    ['Metric', 'Value'],
    ['Total Items Sold', totalItems.toString()],
    ['Total Menu Revenue', formatCurrencyForPDF(totalRevenue)],
    ['Average Revenue per Item', formatCurrencyForPDF(totalRevenue / stats.popularItems.length)],
    ['Most Popular Item', stats.popularItems[0]?.name || 'N/A'],
    ['Highest Revenue Item', stats.popularItems[0]?.name || 'N/A']
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [metricsData[0]],
    body: metricsData.slice(1),
    theme: 'striped',
    headStyles: { fillColor: [16, 185, 129], fontStyle: 'bold' },
    margin: { left: 15, right: 15 }
  });
  
  addFooter(doc, 1, 1);
  
  doc.save(`Menu_Report_${period}_${Date.now()}.pdf`);
};

// Export Complete Report
export const exportCompleteReport = (stats, period, restaurantName) => {
  const doc = new jsPDF();
  
  // PAGE 1: Executive Summary
  addHeader(doc, 'Complete Analytics Report', restaurantName);
  
  let yPos = 50;
  
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(79, 70, 229);
  doc.text('Executive Summary', 15, yPos);
  yPos += 15;
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  
  const summaryData = [
    ['Key Metric', 'Current Value', 'Status'],
    ['Total Revenue', formatCurrencyForPDF(stats.revenue.total), stats.revenue.growth > 0 ? 'Growing' : 'Declining'],
    ['Total Orders', stats.orders.total.toString(), stats.orders.growth > 0 ? 'Growing' : 'Declining'],
    ['Unique Customers', stats.customers.unique.toString(), 'Active'],
    ['Repeat Rate', `${stats.customers.repeatRate.toFixed(2)}%`, stats.customers.repeatRate > 30 ? 'Excellent' : 'Good'],
    ['Average Order Value', formatCurrencyForPDF(stats.revenue.average), 'Steady']
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [summaryData[0]],
    body: summaryData.slice(1),
    theme: 'grid',
    headStyles: { fillColor: [79, 70, 229], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    margin: { left: 15, right: 15 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Customer Insights
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(79, 70, 229);
  doc.text('Customer Insights', 15, yPos);
  yPos += 10;
  
  const customerData = [
    ['Metric', 'Value'],
    ['Unique Customers', stats.customers.unique.toString()],
    ['Repeat Customers', stats.customers.repeat.toString()],
    ['Repeat Rate', `${stats.customers.repeatRate.toFixed(2)}%`],
    ['Customer Loyalty', stats.customers.repeatRate > 30 ? 'High' : 'Medium']
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [customerData[0]],
    body: customerData.slice(1),
    theme: 'striped',
    headStyles: { fillColor: [16, 185, 129], fontStyle: 'bold' },
    margin: { left: 15, right: 15 }
  });
  
  addFooter(doc, 1, 2);
  
  // PAGE 2: Detailed Metrics
  doc.addPage();
  addHeader(doc, 'Detailed Metrics', restaurantName);
  
  yPos = 50;
  
  // Top Items
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(79, 70, 229);
  doc.text('Top 5 Selling Items', 15, yPos);
  yPos += 10;
  
  const topItemsData = [['Rank', 'Item', 'Qty', 'Revenue']];
  stats.popularItems.slice(0, 5).forEach((item, idx) => {
    topItemsData.push([
      `#${idx + 1}`,
      item.name,
      item.quantity.toString(),
      formatCurrencyForPDF(item.revenue)
    ]);
  });
  
  autoTable(doc, {
    startY: yPos,
    head: [topItemsData[0]],
    body: topItemsData.slice(1),
    theme: 'grid',
    headStyles: { fillColor: [236, 72, 153], fontStyle: 'bold' },
    margin: { left: 15, right: 15 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Day of Week Performance
  if (stats.dayOfWeekData && stats.dayOfWeekData.length > 0) {
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(79, 70, 229);
    doc.text('Weekly Performance', 15, yPos);
    yPos += 10;
    
    const weekData = [['Day', 'Orders', 'Revenue']];
    stats.dayOfWeekData.forEach(day => {
      weekData.push([
        day.day,
        day.orders.toString(),
        formatCurrencyForPDF(day.revenue)
      ]);
    });
    
    autoTable(doc, {
      startY: yPos,
      head: [weekData[0]],
      body: weekData.slice(1),
      theme: 'striped',
      headStyles: { fillColor: [139, 92, 246], fontStyle: 'bold' },
      margin: { left: 15, right: 15 }
    });
  }
  
  addFooter(doc, 2, 2);
  
  doc.save(`Complete_Report_${period}_${Date.now()}.pdf`);
};
